### ISSUE TITLE
Updated Dockerfiles

### ISSUE THREAD

**Issue by LudwigEnglbrecht** [shramos/polymorph#11]
Hi,
the Dockerfiles of polymorph need to be updated since the used image is no longer available via docker-hub:

> Please note, kalilinux/kali-linux-docker is the former official image, it’s no longer updated. Don’t use it. [source](https://www.kali.org/docs/containers/official-kalilinux-docker-images/)

Please find attached the updated Dockerfiles with the new base image and the necessary adjustment for using python-netfilterqueue.

Dear @shramos, please check if could be useful :-)

[Dockerfile.txt](https://github.com/shramos/polymorph/files/4365568/Dockerfile.txt)
[Dockerfile-victim.txt](https://github.com/shramos/polymorph/files/4365569/Dockerfile-victim.txt)

**Comment by jayluxferro** [comment]
Hi @LudwigEnglbrecht . Thanks for the updated docker files. Create a pull request so that @shramos  can merge it.

**Comment by LudwigEnglbrecht** [comment]
Dear @jayluxferro , thank you very much for your reply 👍  I created a pull request. Best wishes, Ludwig
