### ISSUE TITLE
"[!] Exception: Error processing the previous command. More info:  name 'os' is not defined" while capture

### ISSUE THREAD

**Issue by mygeone** [shramos/polymorph#14]
Hi @shramos, thanks for updating this project! We are using it as a tool in networking courses.
I'm trying to install Polymorph on a EC2 instance with Ubuntu. 
For installation I did:
`apt-get install build-essential python-dev libnetfilter-queue-dev tshark tcpdump python3-pip wireshark`
`pip3 install git+https://github.com/kti/python-netfilterqueue`
`pip3 install polymorph`
then I added to path:
`export PATH="$PATH:/home/ubuntu/.local/bin/"`
I got ModuleNotFoundError for "dateutil" and "texttable". So I manually installed it.
`pip3 install dateutils` and `pip3 install texttable`
I finally can launch `polymorph` with his main interface but when I try to `capture` I get:
```
PH > capture
[+] Waiting for packets...

(Press Ctr-C to exit)

[!] Exception: Error processing the previous command. More info:

name 'os' is not defined
```
I tried with a Ubuntu/Kali container getting same error as well.

**Comment by shramos** [comment]
Hi @mygeone , 

Thank you for reporting these bugs. I don't understand why I didn't detect them in the test environment before I released the new version.

I have made an upgrade to version 2.0.2 and everything should work fine now. Just uninstall the old version and install the new one.

I am very happy that you are using the tool for your networking workshops, any other problem or suggestion you have, don't hesitate to report it.

Best regards!
