### ISSUE TITLE
Remove spaces at the end to avoid mistakes

### ISSUE THREAD

**Issue by dragonxtek** [shramos/polymorph#18]
Hi Santiago, thanks for your quickly responses
Probably is not an issue, but most software allow to write commands with spaces at the end of line. In this case, it gave me a lot of headaches detect why the error appears, specially when you copy/paste code.

![Selection_999(922)](https://user-images.githubusercontent.com/10552658/95608392-68a22a00-0a33-11eb-9e66-f2420ac03736.png)

**Comment by shramos** [comment]
Good point! I'll fix it in the next update.

**Comment by shramos** [comment]
This issue is already solved in the new update 2.0.5 of Polymorph
