### ISSUE TITLE
Functions with autocomplete

### ISSUE THREAD

**Issue by dragonxtek** [shramos/polymorph#19]
Can you enable autocomplete for functions files?
Actually I can autocomplete with polymorph commands, but no with the arguments suported by `functions -i`
In the example, it would be ideal to autocomplete with the results of `functions -sa`, that is, in this case, with sniff_icmp

![Selection_999(923)](https://user-images.githubusercontent.com/10552658/95611664-832ad200-0a38-11eb-91e2-f49275197e64.png)

**Comment by shramos** [comment]
Hi @dragonxtek, 

In the case you are showing, you can autocomplete by pressing Ctrl+e or simply the right arrow.

**Comment by dragonxtek** [comment]
Sure, but I can do it because I entered the command before and I'm using zshell (remember the lastest commands).
But, if I use bash or I never used this function (like udtforever), I can't autocomplete the sentence to add it quickly

![Selection_999(926)](https://user-images.githubusercontent.com/10552658/95617800-6398a700-0a42-11eb-9fca-441e2f7c1282.png)

**Comment by shramos** [comment]
Polymorph remembers all the commands previously entered by the user, regardless of the shell used. It stores the histories in a series of files located in the project directory. This means that if you have previously created the function, you will always have the option to auto-complete it on subsequent occasions.
