### ISSUE TITLE
iptables dependency? and ip6tables returned 3

### ISSUE THREAD

**Issue by pixal-lab** [shramos/polymorph#22]
Hi,
I installed version 2.0.5 and when I use the command "intercept -localhost", this message appears:

[!] Exception: Error processing the previous command. More info:
Command 'iptables -I OUTPUT -j NFQUEUE --queue-num 1' returned non-zero exit status 127.

Then, i installed the package "iptables" and the message change:

[!] Exception: Error processing the previous command. More info:
Command 'ip6tables -I OUTPUT -j NFQUEUE --queue-num 1' returned non-zero exit status 3.

**Comment by shramos** [comment]
Hi @pixal-lab,

Polymorph establishes two iptables rules to intercept traffic, one for ipv4 traffic and other for ipv6 traffic. 

Try running this sentence `ip6tables -I OUTPUT -j NFQUEUE --queue-num 1` in a separate shell outside Polymorph to check the error. Apparently the first iptables rule has been set correctly and gives problems for the second one, oriented to ipv6 traffic.

Additionally, make sure you are running Polymorph with a user with administration permissions.

**Comment by pixal-lab** [comment]
hi, i found the solution

first, the sentence has the output:
ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

so, the solution was:
for my kernel, i needed an extra module that i installed with the package linux-modules-5.4.0-48-generic
