### ISSUE TITLE
Capture CoAP

### ISSUE THREAD

**Issue by TobalOW** [shramos/polymorph#6]
Hi,

Im trying to capture packets that contains the Constrained Application Protocol but i cant succeed.
CoAP uses UDP with the port 5683, im capturing with only BFG notation "udp" and without filters but i cant reach to the packets.

![screenshot from 2019-01-20 19-45-42](https://user-images.githubusercontent.com/14796868/51446099-0e57b780-1cec-11e9-9f16-2a23fb5262ab.png)
![screenshot from 2019-01-20 19-46-35](https://user-images.githubusercontent.com/14796868/51446106-1f082d80-1cec-11e9-8053-83ee6e3ebef8.png)

At the same time, i capture the packets with Wireshark.

My env:
SO: Ubuntu 18.04
Kernel:  Linux 4.15.0-43-generic

**Comment by shramos** [comment]
Hi!, first of all, thank you for your comment and for using the project. I just did a test with the CoAP protocol, and apparently I have no problem to capture the packets and dissect them correctly. I attached an example:

<img width="702" alt="coap1" src="https://user-images.githubusercontent.com/15182289/52520642-de0c9480-2c6b-11e9-9da1-ff3ad50050cc.png">
<img width="539" alt="coap2" src="https://user-images.githubusercontent.com/15182289/52520645-e2d14880-2c6b-11e9-9ad1-4bf9c4cb1560.png">

Sometimes it is possible that the first dissectors of Polymorph are not able to dissect some protocols, in this cases you can use the `dissect` command after using the `capture` to see if advanced dissectors are capable of detecting it. After applying this command, the CoAP protocol should be detected correctly.

(Another way to perform the advanced dissection is simply by accessing one of those templates that appear with the RAW layer using the `template` command, the advanced dissectors will be applied automatically and Polymorph will try to interpret that RAW layer that has not been able to be dissected in the first capture)
