### ISSUE TITLE
StopIteration exception.

### ISSUE THREAD

**Issue by apheniti** [shramos/polymorph#7]
Hello,
I have installed Poymorph (great project, by the way!), but I can't launch it.
When I type Polymorph in the prompt, a series of unhandled exception arises.

![Cattura](https://user-images.githubusercontent.com/42274043/54088570-b50d1b80-435f-11e9-8166-943c38b67b63.PNG)

I think I have understood that it depends from the **prompt_toolkit** module, but I am unable to fix it. Any ideas of what to change? 
Damn Python 3.7.

**Comment by shramos** [comment]
Hello, 

Thanks for your comment!. I just updated Polymorph's local dependency on prompt-toolkit (which was maintained from when the prompt toolkit project did not support python3 in its stable version).

Can you try reinstalling Polymorph and running it?

**Comment by apheniti** [comment]
It worked like a charm! :) Thanks for the prompt reply!
