### ISSUE TITLE
Polymorph crash when try to read an out of range template

### ISSUE THREAD

**Issue by dragonxtek** [shramos/polymorph#9]
If you capture 6 packets and try to read template number 6, the app crash with this error:

![Selection_421](https://user-images.githubusercontent.com/10552658/71849295-78f63480-30b0-11ea-87cd-24437fa0f589.png)

A message reminding the valid range of templates to choose could be good instead of crash the program.

**Comment by shramos** [comment]
Thanks @dragonxtek. Solved in Polymorph v2.0!
